DROP VIEW IF EXISTS view_fonline_retail;
CREATE VIEW view_fonline_retail
AS

SELECT 
	ID,
	NM_FATURA, 
	CD_ESTOQUE, 
	DESCRICAO, 
	QUANTIDADE, 
	DT_FATURA AS DT_HR_FATURA, 
	DT_FATURA :: DATE AS DT_FATURA,
	VL_UNITARIO, 
	(VL_UNITARIO * QUANTIDADE) VL_FATURA,
	ID_CLIENTE, 
	PAIS,
	CASE
		WHEN QUANTIDADE > 0  THEN 1
		ELSE 0
	END AS FLAG_QUANTIDADE_POSITIVA,
	CASE
		WHEN QUANTIDADE > 0  THEN 'Receita'
		ELSE 'Prejuízo'
	END AS DS_QUANTIDADE_POSITIVA
FROM public.online_retail_refeito
WHERE ID_CLIENTE != 0
AND DESCRICAO NOT LIKE 'nan';