DROP VIEW IF EXISTS view_fonline_stremlit;
CREATE VIEW view_fonline_stremlit
AS

SELECT 
	ID AS ID,
	NM_FATURA AS FATURA,
	CD_ESTOQUE AS CODIGO_ESTOQUE,
	DESCRICAO AS PRODUTOS,
	QUANTIDADE AS QUANTIDADE,
	DT_FATURA AS DATA_HORA_FATURA,
	DT_FATURA :: DATE AS DATA_FATURA,
	VL_UNITARIO AS VALOR_UNITARIO,
	(VL_UNITARIO * QUANTIDADE) AS VALOR_RECEITA,
	ID_CLIENTE AS ID_CLIENTE,
	PAIS AS PAIS,
	CASE
		WHEN QUANTIDADE > 0  THEN 'Receita'
		ELSE 'Prejuízo'
	END AS TIPO_RECEITA
FROM public.online_retail_refeito
WHERE ID_CLIENTE != 0
AND DESCRICAO NOT LIKE 'nan';
